### ISSUE TITLE
[Monitoring / Alerting V2 UI] Feature Overview Page

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#1064]
## UI Overview

The UI for the Feature Overview page will be based off of [this mockup](https://xd.adobe.com/view/62ea899e-acc6-4b72-a654-9ecf811430a8-37b9/).

### External Links

The basic cluster overview page for Monitoring / Alerting V2 need to expose magic links to Prometheus, AlertManager, and Grafana through URLs with the following structure:

**Grafana - View Metrics Dashboards:** `<rancher-url>/k8s/clusters/<cluster-id>/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-grafana:80/proxy`

**Prometheus - View Configured Targets:** `<rancher-url>/k8s/clusters/<cluster-id>/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-prometheus:9090/proxy/targets`

**Prometheus - View Configured Rules:** `<rancher-url>/k8s/clusters/<cluster-id>/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-prometheus:9090/proxy/rules`

**Prometheus - View PromQL Graph:** `<rancher-url>/k8s/clusters/<cluster-id>/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-prometheus:9090/proxy/graph`

**AlertManager - View Active Alerts:** `<rancher-url>/k8s/clusters/<cluster-id>/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-alertmanager:9093/proxy`

As shown in the mockup, there should be sections on the links for 3 components: Grafana UI, Prometheus AlertManager UI, and Prometheus UI. Instead of a single link button shown on the right of each section (in the current mockup), we should have one or more link buttons there corresponding to the various subpaths the user may directly want to go into for each section, i.e.: 
- `Grafana` should have just one link that corresponds to `View Metrics Dashboards`
- `AlertManager` will have just one link that points to `View Active Alerts`
- `Prometheus` will have three links that point to `View PromQL Graph`, `View Configured Targets`, and `View Configured Rules`.

#### Pending Issues

For the Grafana UI and the Prometheus Graph UI, once the page is rendered there are some issue on loading resources due to the specific fields in the Helm chart. This is being tracked in https://github.com/rancher/rancher/issues/28495, but should not impact creating the cluster overview page; as long as the pages above are being rendered at all, the above issue can be tackled as an independent problem.

Related Issues: https://github.com/rancher/dashboard/issues/803, https://github.com/rancher/dashboard/issues/1024

### CRD Explanation

This section will be the content of the `Description` and `What / how` section on the mockup. Instead of using just `What / How` section here, I'd like to have three `What / How` sections; one that explains generally how Monitoring / Alerting is configured and one section each that explains which CRDs actually need to be modified to configure monitoring / alerting individually.
**Top-Level Section**
```
#### Description

This feature enables setting up Monitoring and Alerting within a cluster by deploying a modified version of [Prometheus Operator](https://github.com/prometheus-operator/prometheus-operator), a CoreOS project that simplifies and automates the configuration of a Prometheus-based monitoring stack for Kubernetes clusters, onto your cluster.

In general, any feature supported by the [upstream Prometheus Operator Helm chart](https://github.com/helm/charts/tree/master/stable/prometheus-operator) should be supported in the corresponding version of the chart that deploys this feature. Any deviations introduced in the chart that deploys this feature from the upstream chart will be recorded in a [`CHANGELOG.md`](https://github.com/rancher/charts/blob/dev-v2.5/packages/rancher-monitoring/overlay/CHANGELOG.md) file.

#### Customizing This Feature 

The primary way that users will be able to customize this feature for specific Monitoring / Alerting use cases is by creating / modifying ConfigMaps, Secrets, and Custom Resources pertaining to this deployment.

Prometheus Operator introduces a set of [Custom Resource Definitions](https://github.com/prometheus-operator/prometheus-operator#customresourcedefinitions) that allow users to deploy and manage Prometheus and AlertManager instances by simply creating and modifying those custom resources on a cluster; Prometheus Operator will automatically update your Prometheus configuration based on the live state of these custom resources.

There are also certain special types of ConfigMaps / Secrets such as those corresponding to Grafana Dashboards, Grafana Datasources, and AlertManager Configs that will automatically update your Prometheus configuration via sidecar proxies that are observing the live state of those resources within your cluster.

By default, a set of these resources is created within your cluster as part of deploying this chart to set up a basic Monitoring / Alerting stack. For more information how to configure custom targets, alerts, notifiers, and dashboards after deploying the chart, see below.
```

**Monitoring Section**
```
#### Custom Scrape Configurations, Dashboards, Datasources for Monitoring

Customizing the scrape configuration used by Prometheus to determine which resources to scrape metrics from will primarily involve creating / modifying the following resources within your cluster:
- ServiceMonitors (*insert link to the create servicemonitors page here*): this CRD declaratively specifies how groups of Kubernetes services should be monitored. Any `Services` in your cluster that match the labels located within the ServiceMonitor `selector` field will be monitored based on the `endpoints` specified on the ServiceMonitor. For more information on what fields can be specified, please look at the [spec](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#servicemonitorspec) provided by Prometheus Operator.
- PodMonitors (*insert link to the create podmonitors page here*): this CRD declaratively specifies how group of pods should be monitored. Any `Pods` in your cluster that match the labels located within the PodMonitor `selector` field will be monitored based on the `podMetricsEndpoints` specified on the PodMonitor. For more information on what fields can be specified, please look at the [spec](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#podmonitorspec) provided by Prometheus Operator.

Once these resources are added into the cluster, you can check to see if Prometheus picks them up by viewing the  Configured Targets (*insert external URL link from above `<rancher-url>/k8s/clusters/<cluster-id>/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-prometheus:9090/proxy/targets`*) on the Prometheus UI. 

You can then try out PromQL queries based on the metrics pulled from those Configured Targets by navigating to the PromQL Graph (*insert external URL link from above `<rancher-url>/k8s/clusters/<cluster-id>/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-prometheus:9090/proxy/graph`*) on the Prometheus UI.

Once you have confirmed that the metrics you want are being collected and can be queried by Prometheus, you should navigate to the Grafana UI (*insert external URL link from above ``*) and follow the instructions from the [Grafana `Getting Started` docs](https://grafana.com/docs/grafana/latest/getting-started/getting-started/) to create a dashboard. 

Once a dashboard has been created, you should follow the instructions from the [Grafana `JSON Model` docs](https://grafana.com/docs/grafana/latest/reference/dashboard/) to extract the JSON and persist it in a ConfigMap (*insert link to create Grafana Dashboard ConfigMap page here*) as specified in the [Grafana helm chart docs](https://github.com/helm/charts/tree/master/stable/grafana#sidecar-for-dashboards) within the `grafana_dashboards` namespace. This persists the dashboard within your cluster in case the Grafana deployment needs to be restarted.

##### Advanced Use Cases

If the scrape configuration you want cannot be specified via a ServiceMonitor or PodMonitor at the moment, you can provide an `additionalScrapeConfigSecret` on deploying / upgrading this feature chart that provides a scrape configuration based on the [Prometheus docs](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config).

If you would like to add [recording rules](https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/) to define a frequently needed or computationally intensive PromQL query that should be stored as a new set of time series, you should create a PrometheusRule (*insert link to the create prometheusrules page here*). Creating the desired recording rule will involve creating or updating a RuleGroup with your desired recording rule; each recording rule needs to name the new time series, provide a PromQL expression for the series, and provide any labels that need to be added to this series. For more information on what fields can be specified, please look at the [spec](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#prometheusrulespec).

If you would like to add other datasources to Grafana, you should persist the configuration in a ConfigMap (*insert link to create Grafana Datasource ConfigMap page here*) as specified in the [Grafana helm chart docs](https://github.com/helm/charts/tree/master/stable/grafana#sidecar-for-datasources) within the `grafana_datasources` namespace so that it will be persisted in case the Grafana deployment needs to be restarted.
```

**Alerting Section**
```
#### Alerting Rules and Notifiers for Alerting

Customizing the alerts recorded by Prometheus and the configuration of notifiers that should notify users when alerts are triggered will primarily involve creating / modifying the following resources within your cluster:
- PrometheusRules (*insert link to the create PrometheusRuleSpec page here*): this CRD defines a desired set of Prometheus alerting and/or recording rules. Creating the desired alerting rule will involve creating or updating a RuleGroup with your desired alerting rule; each alerting rule needs to name the alert, provide a PromQL expression for the alert, and provide any labels / annotations that need to be sent to AlertManager on the alert. Labels are concise values that identify the alert (e.g. cluster name or severity), while Annotations contain other important pieces of information that need to be displayed when notifying users about an alert (e.g. summary, description, message, runbook URL, etc.). For more information on what fields can be specified, please look at the [spec](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#prometheusrulespec).
- AlertManager Config (*insert link to view the specific AlertManager Config tied to the main Prometheus here*): this Secret will contain the configuration of an Alertmanager instance that sends out notifications based on alerts it receives from Prometheus. This Secret should be updated / modified any time you want to add in new notifiers / receivers, change the alerts that should be sent to specific notifiers / receivers, or change the group of alerts that are sent out. For more information on what fields can be specified in this secret, please look at the [Prometheus AlertManager Configuration docs](https://prometheus.io/docs/alerting/latest/configuration/).

##### Advanced Use Cases

By default, Rancher's AlertManager Config Secret includes a key for a default `rancher_defaults.tmpl` that automatically formats the alerts sent out by Alertmanager based on the existence of certain default labels / annotations defined as part of the alerting rule. If you would like to customize the template that is used to generate alerts for different notifiers, you can add new keys to the AlertManager Config Secret corresponding to template files that will be stored in `/etc/alertmanager/config/<key-name>` and reference them as part of the AlertManager Config. For more information on what how to specify a `templateFile` on this secret, please look at the [Prometheus AlertManager Configuration docs](https://prometheus.io/docs/alerting/latest/configuration/).
```

### CRD Summary

This is a nice-to-have followup that will be tracked in a separate ticket here: https://github.com/rancher/dashboard/issues/1175

**Comment by deniseschannon** [comment]
@aiyengar2 Would it make sense to have a summary of any of the CRDs on this page? What would/could make sense?

**Comment by deniseschannon** [comment]
@lvuch can you work with @aiyengar2 to add in some icons along with these links so it's more graphical/pretty/sizzle-y

**Comment by aiyengar2** [comment]
> @aiyengar2 Would it make sense to have a summary of any of the CRDs on this page? What would/could make sense?

@deniseschannon I think describing the CRDs in the Cluster Overview page directly could be done, but it could be really cool if instead we have a button that links to a page similar to the `Workload: Create` page for `Monitoring: Create` that allows users to create the CRs for ServiceMonitors, PodMonitors, PrometheusRules, Grafana Dashboards, and Grafana Datasources. It would make sense to add descriptions for each of these CRs here instead of to the Cluster Overview page directly.

UI Reference:

![Screen Shot 2020-08-20 at 3 40 42 PM](https://user-images.githubusercontent.com/13127443/90832861-9a342a00-e2fb-11ea-931b-0fea9d6754ff.png)

For this page, I think it would make sense to add descriptions for Prometheus, Grafana, and AlertManager, but not necessarily the CRDs themselves since it is assumed that most users should be using the default Prometheus / AlertManager CRs that Rancher provides without any modifications post-deployment.

**Comment by westlywright** [comment]
@maggieliu @deniseschannon this was moved to `next but I dont feel like we have enough info here to really push on this. It doesn't look we've fully fleshed out what the overview page looks like as there are questions hanging around.

**Comment by deniseschannon** [comment]
MVP:
External Links 
Description/How-tos

Nice to Have:
CRD Summary

**Comment by aiyengar2** [comment]
> MVP:
> External Links
> Description/How-tos
> 
> Nice to Have:
> CRD Summary 

CRD Summary now tracked in a separate ticket here: https://github.com/rancher/dashboard/issues/1175

**Comment by lvuch** [comment]
<img width="583" alt="Screen Shot 2020-09-08 at 11 01 27 AM" src="https://user-images.githubusercontent.com/3013118/92511785-ab69ab80-f1c2-11ea-9dc6-53f2716c05e9.png">

**Comment by aiyengar2** [comment]
The links on the feature overview page should only show up if the `rancher-monitoring` chart is installed, not just based on the existence of the CRDs. The reason why this is required is for users migrating from Monitoring V1 to Monitoring V2; since the CRDs are installed onto the cluster, the UI currently detects that the feature is installed and allows the user to navigate to the Monitoring page; however, if they click on any of the links, they'll see the following error.

![Screen Shot 2020-09-15 at 5 38 01 PM](https://user-images.githubusercontent.com/13127443/93278678-3544e600-f77a-11ea-9b03-5e6ee86652fc.png)

Since migrating from Monitoring V1 to Monitoring V2 is a fairly common use case we expect, this should be prioritized to prevent users from viewing broken links on upgrade.

**Comment by aiyengar2** [comment]
### Other Bugs / Comments

#### Highlighting the Alertmanager link covers the text above it

![Screen Shot 2020-09-15 at 5 39 28 PM](https://user-images.githubusercontent.com/13127443/93278766-69200b80-f77a-11ea-8f37-6053e2aa4c19.png)

#### Link format

Also, can we change the links to use the following names directly (rather than having it visible on highlight):
> - `Grafana` should have just one link that corresponds to `View Metrics Dashboards`
> - `AlertManager` will have just one link that points to `View Active Alerts`
> - `Prometheus` will have three links that point to `View PromQL Graph`, `View Configured Targets`, and `View Configured Rules`.

I think it would be nicer if we had the three Prometheus buttons on one line and the Grafana / Alertmanager links on the second line instead of the current 4 and 1.

**Comment by aiyengar2** [comment]
Also @deniseschannon I think the feature overview page needs more text since it looks super bland at the moment; just a ton of buttons with no particular context. Can we add in the CRD Explanation stuff (or a more concise version of that) so that there's some sort of text on the page or directions to the user on what they should click on next to configure monitoring?

We also should add a description to the CRD pages like below:

![Screen Shot 2020-09-15 at 1 32 01 PM](https://user-images.githubusercontent.com/13127443/93279290-be105180-f77b-11ea-9ee7-771c5212f16c.png)

**Comment by aiyengar2** [comment]
https://github.com/rancher/dashboard/issues/1260 needs to be addressed with this

**Comment by westlywright** [comment]
@jiaqiluo I have addressed the follow:

https://github.com/rancher/dashboard/issues/1064#issuecomment-693102044 - Links will not show up if they do not exist
https://github.com/rancher/dashboard/issues/1064#issuecomment-693104014 - Dropped the tooltip on hover, Moved the content of those tooltips to the link text. We will not be changing the count per row as this is dynamic based on screen size. And I'll break the image comment into a new ticket. 
https://github.com/rancher/dashboard/issues/1064#issuecomment-693105327 - This should be addressed when we move past the MVPs and start adding CR info.

**Comment by jiaqiluo** [comment]
the bug fix is validated in master-head with the latest UI 

1. When monitoring is not installed, the monitoring overview page still shows in the dashboard, but the count is 0 for resources and links are not clickable (`resource Unavailable` shows)
<img width="857" alt="Screen Shot 2020-09-25 at 11 01 37 AM" src="https://user-images.githubusercontent.com/6218999/94302014-64005080-ff20-11ea-89ee-a14d3044d5d4.png">

2. the tooltips on hover are moved to the icons' name. For example, `AlertManager` becomes `AlertManager - Active Alerts`
