### ISSUE TITLE
[Bug] Cannot create RKE2 cluster from yaml view

### ISSUE THREAD

**Issue by jordojordo** [rancher/dashboard#11020]
**Setup**
- Rancher version: `v2.9-head`  (`2b53406`) 
- Rancher UI Extensions: N/A
- Browser type & version: FF 125.0.3

**Describe the bug**

When attempting to provision an RKE2 cluster from the YAML view, the formatting of the generated yaml is incorrect, causing the creation to fail.

**To Reproduce**

- Install Rancher `v2.9-head` 
- Create RKE2 cluster
- Select "Edit as YAML"
- Attempt to create the cluster

**Result**
An error banner shows:

<details open>

```console
bad indentation of a mapping entry (13:56)

10 | ...
11 | ... t
12 | ...
13 | ... ustomization: overrideAffinity: {}
-----------------------------------------^
14 | ...
15 | ... ments: {}
```

</details>

**Screenshots**

![rke2-yaml](https://github.com/rancher/dashboard/assets/40806497/83d6ee5b-b4e8-4a87-b952-8d93473a588e)

**Additional context**

It appears that the schema returned is broken, there are a few instances with incorrect spacing and two duplicate entries.

- Incorrect spacing:
  - `clusterAgentDeploymentCustomization: overrideAffinity: {}`
  - `fleetAgentDeploymentCustomization: overrideAffinity: {}`
  - `rkeConfig: chartValues:`
- duplicate entries:
  - `appendTolerations: []`
  - `overrideResourceRequirements: {}`

<details open><summary>Yaml returned for rke2 config</summary>

```yaml
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: #string
  annotations:
    {}
    #  key: string
  labels:
    {}
    #  key: string
  namespace: fleet-default
spec:
  clusterAgentDeploymentCustomization: overrideAffinity: {}
  appendTolerations: []
  overrideResourceRequirements: {}
  defaultPodSecurityAdmissionConfigurationTemplateName: ''
  fleetAgentDeploymentCustomization: overrideAffinity: {}
  appendTolerations: []
  overrideResourceRequirements: {}
  kubernetesVersion: v1.28.9+rke2r1
  localClusterAuthEndpoint:
    caCerts: ''
    enabled: false
    fqdn: ''
  rkeConfig: chartValues:
    rke2-calico: {}
  upgradeStrategy:
    controlPlaneConcurrency: '1'
    controlPlaneDrainOptions:
      deleteEmptyDirData: true
      disableEviction: false
      enabled: false
      force: false
      gracePeriod: -1
      ignoreDaemonSets: true
      skipWaitForDeleteTimeoutSeconds: 0
      timeout: 120
    workerConcurrency: '1'
    workerDrainOptions:
      deleteEmptyDirData: true
      disableEviction: false
      enabled: false
      force: false
      gracePeriod: -1
      ignoreDaemonSets: true
      skipWaitForDeleteTimeoutSeconds: 0
      timeout: 120
  machineGlobalConfig:
    cni: calico
    disable-kube-proxy: false
    etcd-expose-metrics: false
    profile: null
  machineSelectorConfig:
    - config:
        protect-kernel-defaults: false
  etcd:
    disableSnapshots: false
    s3: null
    snapshotRetention: 5
    snapshotScheduleCron: 0 */5 * * *
  registries:
    configs: {}
    mirrors: {}
  machinePools: []
  machineSelectorConfig:
    - config: {}
#  agentEnvVars: string
#  cloudCredentialSecretName: string
#  clusterAPIConfig: string
#  defaultClusterRoleForProjectMembers: string
#  defaultPodSecurityPolicyTemplateName: string
#  enableNetworkPolicy: string
#  redeploySystemAgentGeneration: int
__clone: true
```

</details>

**Comment by richard-cox** [comment]
It looks like a lot of the spec props have lost their hierarchy 

![image](https://github.com/rancher/dashboard/assets/18697775/968494b1-597b-480d-b529-90f893ea2f3b)

The `schema` looks ok, we should check value that goes into the yaml converter

**Comment by richard-cox** [comment]
This _might_ be impacted by https://github.com/rancher/rancher/issues/45157, but we should still confirm the json object we convert to yaml is correct

**Comment by tomleb** [comment]
@richard-cox I'm working on https://github.com/rancher/rancher/issues/45157 now. I need to rebase my changes on top of @MbolotSuse 's fix, which was also affecting the schema definitions. Once that's done (by EOD) I'll ping you.

**Comment by richard-cox** [comment]
Tom has kindly got an image ready for us to test with, check in with him for details

**Comment by nwmac** [comment]
@aalves08 This is one you could pick up if you have capacity - check with @richard-cox  - first step is to validate if this is still an issue with the test backend provided

**Comment by gaktive** [comment]
Possibly connected with #10330

**Comment by aalves08** [comment]
Waiting for merging of https://github.com/rancher/dashboard/issues/11020#issuecomment-2111871498 + providing of a new image to check if this has been fixed by the backend

**Comment by tomleb** [comment]
@aalves08 

The PR is still being worked on but it already fixes _some_ issues so it could be worth a shot validating that it also fixes this issue before my PR is merged. I've pushed a custom build of rancher based [on the latest v2.9 commit](https://github.com/rancher/rancher/tree/71c10185d52f3e1dc30b941317c71805133e6a17) at this time:
- Rancher: `docker.io/tlebreux/rancher@sha256:bab9148739bcf61ddec5b0f9a39a1b3eb40d8b297436bc1dde179d003f3b3de9`
- Rancher agent: `docker.io/tlebreux/rancher-agent:schema-fix@sha256:9137b1ad0f61d86dd67b39a996bfe52db14f1a9add065377b1cfe5e89aa998bc`

To use it, you can use something like the following (or whatever you use to run rancher with specific images):

```
docker run -d --restart=unless-stopped -p 8080:80 -p 8081:443 -p 8082:6060 --name rancher --env CATTLE_AGENT_IMAGE=docker.io/tlebreux/rancher-agent:schema-fix@sha256:9137b1ad0f61d86dd67b39a996bfe52db14f1a9add065377b1cfe5e89aa998bc --privileged docker.io/tlebreux/rancher@sha256:bab9148739bcf61ddec5b0f9a39a1b3eb40d8b297436bc1dde179d003f3b3de9
```

**Comment by aalves08** [comment]
@gaktive I don't have time to look at this issue. Can someone else pick it up?

FYI @nwmac

**Comment by gaktive** [comment]
@aalves08 will kick the tires on the Docker image and if it doesn't work, we need to hand this off.

**Comment by aalves08** [comment]
I've taken some time yesterday to run the docker image and I cannot get it to work....

Via docker (DO droplet with Ubuntu 20.04 - won't work in Mac's since it's not built in arm):
```
docker run -d --restart=unless-stopped --env CATTLE_DEV_MODE=30 --env CATTLE_AGENT_IMAGE=docker.io/tlebreux/rancher-agent:schema-fix@sha256:9137b1ad0f61d86dd67b39a996bfe52db14f1a9add065377b1cfe5e89aa998bc --privileged --network host --privileged docker.io/tlebreux/rancher@sha256:bab9148739bcf61ddec5b0f9a39a1b3eb40d8b297436bc1dde179d003f3b3de9   --trace=false --add-local=true --no-cacerts --features=harvester=false
```

and via helm:
```
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=209.97.184.234.sslip.io \
  --set rancherImage=docker.io/tlebreux/rancher \
  --set rancherImageTag=schema-fix@sha256:bab9148739bcf61ddec5b0f9a39a1b3eb40d8b297436bc1dde179d003f3b3de9 \
  --set 'extraEnv[0].name=CATTLE_AGENT_IMAGE' \
  --set 'extraEnv[0].value=docker.io/tlebreux/rancher-agent:schema-fix@sha256:9137b1ad0f61d86dd67b39a996bfe52db14f1a9add065377b1cfe5e89aa998bc' \
  --set bootstrapPassword=password \
  --devel
```

I have to pass this to another developer @gaktive 🙏  sorry about that. Thanks for the help @tomleb  🙇

**Comment by richard-cox** [comment]
I managed to bring up rancher in docker locally. However couldn't get to the provision a d/s cluster

Cluster Management --> Clusters --> Create --> Digital Ocean RKE2 --> `Create`. Error `No version info found in KDM`
- https://localhost:8081/v1-k3s-release/channels and https://localhost:8081/v1-rke2-release/channels are empty

Normally Cluster Management --> Drivers --> `Refresh Kubernetes Metadata` will resolve that kind of error in other dev images, however this failed
- https://localhost:8081/v3/kontainerdrivers?action=refresh - `failed to refresh failed to create or update driverMetadata: driverMetadata: unable to find default k8s version in current k8s v1.29.x [v1.10.12-rancher1-1 v1.11.9-rancher1-3 v1.12.10-rancher1-2 v1.13.12-rancher2-1 v1.14.10-rancher1-1 v1.15.12-rancher1-1 v1.16.7-rancher1-1 v1.17.3-rancher1-1 v1.18.17-rancher1-3 v1.22.17-rancher1-2 v1.8.11-rancher2-1 v1.9.7-rancher2-2]`

I checked the `setting` `rke-metadata-config` and it points to https://releases.rancher.com/kontainer-driver-metadata/dev-v2.9/data.json, which matches a working instance.

docker logs contains
```
[ERROR] failed to reload configuration from https://releases.rancher.com/kontainer-driver-metadata/dev-v2.9/data.json: failed to get release config: Short version cannot contain PreRelease/Build meta data
```

Bringing up in DO hit a different issue, i've never seen that work with fleet coming up succesfully.

Bringing up in DO with helm hit cert-manager issues once rancher came up.

@tomleb How long are we away from the fixes being available in `v2.9-head`

**Comment by richard-cox** [comment]
#11225 and #11226 should be checked along with this issue

**Comment by tomleb** [comment]
@richard-cox 
> How long are we away from the fixes being available in v2.9-head

The fix is now in steve `master`, we need to update steve version in rancher/rancher but we need https://github.com/rancher/rancher/pull/45483 to be able to do that (steve uses wrangler v3, rancher/rancher currently uses wrangler v2)

**Comment by gaktive** [comment]
Ties into the k8s 1.30 bump based on the PR above. @Sahota1225 keep UI & @tomleb on 1.30's progress since a couple bugs await that now.

**Comment by gaktive** [comment]
1.30 bump is in though I need to check the status of the related tickets but this may be unblocked, along with a couple dashboard tix.

**Comment by MbolotSuse** [comment]
@gaktive With the merge of rancher/rancher#45928 this should be resolved. Please let @tomleb or I know if there are further issues here.

**Comment by richard-cox** [comment]
Following backend changes, i tried to reproduce in `v2.9-a84c3a2f` and could not. 

We just need to write some automation to prevent regression.

**Comment by IsaSih** [comment]
Same error still occurs. UI and dashboard latest and remote. Tested on

![Image](https://github.com/rancher/dashboard/assets/70187881/546c5533-8b71-49c3-a89e-079939852250)

 v2.9-3ae1c6ac8d3524f8ded4544f1db75fc9e07911a5-head

**Comment by richard-cox** [comment]
3ae1c6a is quite old (two weeks - https://github.com/rancher/rancher/commits/release/v2.9/?after=d2fa8a7d6116c48a814ee7983af522d614461e49+104), there's a good chance it doesn't contain the fix.

@IsaSih can you give a try with the latest rancher (if using docker all-in-one make sure to `docker pull` the image first)?

**Comment by sowmyav27** [comment]
Reproduced the issue on `v2.9.0-alpha5`
<img width="1055" alt="Screen Shot 2024-07-10 at 8 59 30 AM" src="https://github.com/rancher/dashboard/assets/26032343/83db4d42-66b9-4274-9160-d55587b63cc4">

On `v2.9-a9355` and dashboard - `master 30d8ecc`, this issue is not seen anymore. User is able to create an RKE2 node driver cluster from YAML view.
