### ISSUE TITLE
Vue3: Workload Container Storage tab renders volume drop down incorrectly

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11781]
**Setup**
- Rancher version: dev of 2.10.0

**Describe the bug**
- drop down squished
- same for the Pod tab -> Storage vertical tab (generic component broken, or broken in context?)

**To Reproduce**
- Cluster Explorer --> Workloads --> Deployments --> initial container tab --> Storage vertical tab

**Result**
![image](https://github.com/user-attachments/assets/815b0c3a-6df8-463b-80e9-dcb4cbb1b7a8)

**Expected Result**
![image](https://github.com/user-attachments/assets/e0010ff9-bd8f-4a94-bc97-68ef210f453e)

**Comment by richard-cox** [comment]
Possibly resolved via https://github.com/rancher/dashboard/pull/11788

**Comment by rak-phillip** [comment]
Confirmed to be resolved

**Comment by IsaSih** [comment]
Dropdown behaviour seems to be partially resolved. It displays the options as expected on both the pod and the container tab.  However, for the container tab, as seen in the screen recording, the values the user selects from the dropdown are not actually being selected. 

![Image](https://github.com/user-attachments/assets/8c5e9d83-5b5c-41e9-93db-0c6333bdc5e7)

And when trying to create the deployment, the following error occurs:

**Comment by rak-phillip** [comment]
@IsaSih can we create new issues for each of these regressions that you identified? There were several issues identified with this area of dashboard and I want to ensure that we track additional problems properly.

**Comment by rak-phillip** [comment]
@IsaSih yes, let's close this one and focus on the new bug to address the noted regressions.
