### ISSUE TITLE
[Logging v2] - Deploy to control plane nodes is always active even then unchecked when installing

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#1320]
Rancher version `master-head (09/19/2020)` _ bd88c23_

 - Install Rancher HA k8s.
- Downstream cluster is RKE DO or k3s/rke2/EKS
- Navigate to Dashboard and Apps
- Click `rancher-logging`
- Chart Options leave `Deploy to control plane nodes` unchecked
- Preview YAML

Values YAML generates:

```yaml
additionalLoggingSources:
  eks:
    enabled: false
  k3s:
    container_engine: systemd
    enabled: true
  rke:
    enabled: false
  rke2:
    enabled: false
.....
```

![Screen Shot 2020-09-19 at 8 02 22 PM](https://user-images.githubusercontent.com/27659/93693327-3a27d380-fab3-11ea-9212-89b174b67cdd.png)

![Screen Shot 2020-09-19 at 8 03 34 PM](https://user-images.githubusercontent.com/27659/93693329-3dbb5a80-fab3-11ea-9e6b-808ab8b4d91e.png)

**Comment by codyrancher** [comment]
I fixed another issue with deployToControlPlane and can't reproduce this issue. Can you take a look again?

**Comment by izaac** [comment]
Rancher version: `master-head (09/29/2020)` _a2a141e_

I'm still getting the Control Plane log collectors installed even if I leave that chart option unchecked.

This is an RKE cluster for example:


![Screen Shot 2020-09-29 at 5 59 04 PM](https://user-images.githubusercontent.com/27659/94631809-b2458480-027d-11eb-8e02-8b64e178350d.png)

![Screen Shot 2020-09-29 at 5 58 12 PM](https://user-images.githubusercontent.com/27659/94631811-b5d90b80-027d-11eb-8ce0-6c2684231c6c.png)

![Screen Shot 2020-09-29 at 6 00 29 PM](https://user-images.githubusercontent.com/27659/94631816-b83b6580-027d-11eb-996d-9b38c55acfab.png)

**Comment by codyrancher** [comment]
@paynejacob the frontend seems to be passing the appropriate values for fluentbit_tolerations. Is this a backend issue?

disabled:
![Screen Shot 2020-09-30 at 11 26 57 AM](https://user-images.githubusercontent.com/55104481/94725121-23357c80-0310-11eb-8e69-f8b526451fe3.png)

enabled:
![Screen Shot 2020-09-30 at 11 26 28 AM](https://user-images.githubusercontent.com/55104481/94725123-23ce1300-0310-11eb-9461-d15b819ffe35.png)

**Comment by paynejacob** [comment]
That is a backend issue if the tolerations are being passed.

**Comment by codyrancher** [comment]
Alright, assigning @paynejacob. Let me know if there are any frontend changes that are needed to support the backend.
