### ISSUE TITLE
Fleet: Gitrepo: Polling interval automatically set to 15s when using default value of 60s

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/dashboard#13824]
**Setup**
- Rancher version: v2.11

**Describe the bug**
The polling interval automatically set to 15s when using default value of 60s when creating a Gitrepo.

**To Reproduce**
1. go to Continuous delivery => Gitrepos => fleet-local workspace
2. click Add Repository
3. create Gitrepo (keep polling interval as default i.e. 60)
```
https://github.com/rancher/fleet-examples
branch: master
path: simple
```
4. Edit Config => Advanced => scroll down to Polling section
5. notice polling interval set to 15s

**Result**
Polling interval automatically set to 15s when using default value of 60s.

**Expected Result**
Polling interval set to 60s (default value) unless the user updates it.

**Screenshots**

https://github.com/user-attachments/assets/e061a55b-bdb0-4cad-84c8-b8ff108eef4e

**Additional context**
Discovered while testing: https://github.com/rancher/dashboard/issues/13661

**Comment by gaktive** [comment]
This may have to fixed in 2.11.0 so holding off on backport for now until this is assessed.

**Comment by a-arias** [comment]
**TESTS**

Rancher | v2.12-d7f62116eb48fb060f02a10c8b01164048d9eeda-head
Dashboard | master https://github.com/rancher/dashboard/commit/01a2d88593058b075515a71a7e6d68e07b0da411


I am still seeing the polling interval not correct after creation of the git repo ❌

https://github.com/user-attachments/assets/89682551-e3dc-4fda-97b1-77410c8ea34a
 
User needs to open configuration twice to see correct interval.

**Comment by torchiaf** [comment]
> **TESTS**
> 
> Rancher | v2.12-d7f62116eb48fb060f02a10c8b01164048d9eeda-head Dashboard | master [01a2d88](https://github.com/rancher/dashboard/commit/01a2d88593058b075515a71a7e6d68e07b0da411)
> 
> I am still seeing the polling interval not correct after creation of the git repo ❌
> 
>  bug.still.present.mov 
> User needs to open configuration twice to see correct interval.

It seems to be correct actually, the difference between the UI value and Yaml is the format. Fleet changes 60s to 1m0s after saving, but the result is the same in terms of functionality.
I'd say, unless the YAML and UI chnage in absolute value, we are fine.
WDYT @a-arias ?

**Comment by yonasberhe23** [comment]
Thanks for looking into this @torchiaf. I think we're good to close this out.
