### ISSUE TITLE
Extensions can override Toplevel Nav styles

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#15553]
**Setup**
- Rancher version: Rancher Head
- Rancher UI Extensions: NA
- Browser type & version: Firefox & Chrome

**Describe the bug**

Installed extensions have the ability to override Toplevel Nav styles in Rancher Shell.

**To Reproduce**

1. Install Code Zero - the newly added icon is correct
2. Install Supportability Review

**Result**

Extension icon styles in the Toplevel Nav are mutated

**Expected Result**

Styles remain as they are defined in the host instance

**Screenshots**

<img width="1376" height="1234" alt="Image" src="https://github.com/user-attachments/assets/193290ef-3f48-425a-85fc-ca1a8bce5c82" />

<img width="1376" height="1234" alt="Image" src="https://github.com/user-attachments/assets/06cd9077-0511-4d47-a0b4-8887a1188c32" />

**Additional context**

**Comment by nwmac** [comment]
@rak-phillip I think this may have been fixed - but there is an issue with the color change that we do for extensions when they provide SVGs - the hover color is wrong - looks like we're still using `--link` whereas the icon based icons use `--on-tertiary`

**Comment by rak-phillip** [comment]
@nwmac I just tested with a newly deployed head image - this issue is not fixed. Reproduced by first installing CodeZero and then installing CloudCasa - the inclusion of CloudCasa mutates the colors of the svg icons: 

<img width="67" height="441" alt="Image" src="https://github.com/user-attachments/assets/aea1a8d5-d2cc-4079-a0d8-4c376e8c5579" />

<img width="67" height="441" alt="Image" src="https://github.com/user-attachments/assets/e42e85a9-f22a-4c3a-a954-cbe99b1a2a09" />


> looks like we're still using --link whereas the icon based icons use --on-tertiary

`--on-tertiary` is defined as `--on-tertiary: var(--link);` and will evaluate to the same value as `--link`. We can fix this so that all svgs use `--on-tertiary`, but I still believe there to be a leaky abstraction with how extensions handle css.

https://github.com/rancher/dashboard/blob/085a1151b5d03c51c3cf56bfdacf59055211e90f/shell/assets/styles/themes/_modern.scss#L102

**Comment by nwmac** [comment]
@rak-phillip It will in the CSS, but we have code which generates a css filter to change the SVG color - as this is something can not be done easily, otherwise - see: `svg-filter.js` used in `https://github.com/rancher/dashboard/blob/master/shell/components/IconOrSvg.vue#L36`

**Comment by rak-phillip** [comment]
Yes, and it appears to be `IconOrSvg` that introduces the problem by injecting global styles, allowing extensions to override styles specified in shell: 

https://github.com/rancher/dashboard/blob/085a1151b5d03c51c3cf56bfdacf59055211e90f/shell/components/IconOrSvg.vue#L119-L146

**Comment by rak-phillip** [comment]
I have a very rough draft for how we might resolve this issue raised in #16022. My thought process is that we can utilized the `v-bind` in css vue3 feature to ensure that svg styles are scoped.. We need a level of specificity that reaches beyond the component itself to prevent extensions from overriding styles, but it appear to guard extensions that play nice while breaking those that don't:

<img width="68" height="524" alt="Image" src="https://github.com/user-attachments/assets/22c6fc73-66e8-439f-bb71-00385e62466a" />

I'll spend some more time trying to improve the situation. At this point I'm unsure if we'll be able to keep extension compatibility with the new theme for offending extensions like CloudCasa and Supportability Review.

**Comment by oboc-sts** [comment]
The Observability team reported this as well 

<img width="269" height="494" alt="Image" src="https://github.com/user-attachments/assets/94a65826-e312-4c3e-9246-012a6dbd5b49" />

**Comment by a-arias** [comment]
**To Test**
Fix validated ✅
Rancher : v2.15-ceab2a8859b543207ad81ea66b3497e44ddebcce-head
UI: master 60fe328

https://github.com/user-attachments/assets/e74e15b5-422b-45ef-bb6c-958ac38c4a7c
