### ISSUE TITLE
Workload pods list does not live add/remove matching pods

### ISSUE THREAD

**Issue by vincent99** [rancher/dashboard#2218]
If you redeploy a workload (related: #1810) the list of pods for a workload will show them go to Terminating state but never disappear, and not pick up the new pods that replaced them because the `workload.pods` isn't a "live" array.

**Comment by gaktive** [comment]
Fixed now by PR: https://github.com/rancher/dashboard/pull/2285

**Comment by thehejik** [comment]
I was able reproduce this issue and also https://github.com/rancher/dashboard/issues/1810 (redeploy without effect) on `v2.5.6-rc2` - the pods were not recreated at all on attempt to Redeploy of my nginx deployment.

Now on `v2.5.6-rc4` and also on `rancher/rancher:master-head` the pods are successfully recreated on attempt to Redeploy the deployment (this part fixed within #1810).

But the description of this issue is still valid even for newest `rancher/rancher:master-head` because the Pods on Workload/Deployment page are visually stuck in `Terminating` state and it's not going to change until user manually reload the page.

Using `rancher/rancher:master-head`  master-d7203b4ba0e46ba794b3dfa27cb10f5904dd3890-head with User Interface  `vmaster-dev`

![dashboard_redeploy](https://user-images.githubusercontent.com/12828077/108223286-f1477a00-7139-11eb-8f42-c7522cc57345.png)

**Comment by thehejik** [comment]
The issue still reproducible in rancher v2.5.6-rc5 but as you can see bellow it has been fixed in rancher master-head (465bb3b) image.
![live_pods](https://user-images.githubusercontent.com/12828077/109154489-a0a1d380-776e-11eb-8d04-d0b07f37fcc1.gif)

@mantis-toboggan-md should I create a follow up issue for v2.5.x before closing?

**Comment by thehejik** [comment]
It does work correctly with `v2.5-head` on top of `rancher:2.5.6-rc5` so I'm closing this issue.

Tested on `v2.5-1b5aad6fec0ca35d4e9314f7f79cc0a8a85ccff5-head`.
