### ISSUE TITLE
After upgrade to rancher 2.5.6 HA mode resource unavailable

### ISSUE THREAD

**Issue by nickvth** [rancher/dashboard#2494]
- After upgrade to rancher 2.5.6 HA mode I get resource unavailable for grafana, prometheus ui etc. 

- I am cluster-admin 
- When creating the url in the browser it work (example): https://[fqdn]/k8s/clusters/[cluster-id]/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-grafana:80/proxy/?orgId=1  

No errors in rancher log..

**Comment by aquam8** [comment]
I have the same problem on my EKS private cluster.

If I can add anything it is that the XHR request to get the endpoints is working, I get 200 and a valid response from `https://[fqdn]/k8s/clusters/[cluster-id]/v1/endpoints`
The response data contains the entries matching the expected ID `cattle-monitoring-system/rancher-monitoring-grafana` to enable the monitoring resource for Grafana.

I'm adding a screenshot of the response in case that helps.
![image](https://user-images.githubusercontent.com/181863/110551610-efe1fe00-8189-11eb-82bf-87ef1375c706.png)

Logic is here from what I can see: https://github.com/rancher/dashboard/blob/master/pages/c/_cluster/monitoring/index.vue

**Comment by aiyengar2** [comment]
If this is a permissions issue, there's more information on https://github.com/rancher/dashboard/issues/2408 regarding what permissions we expect today w.r.t. being able to view the Monitoring links. 

At the moment, we expect that you can view all workloads in at least one namespace / project and manage services in the namespace / project that contains Rancher Monitoring within it.

**Comment by nickvth** [comment]
@aiyengar2  it's not a permission issue, because I am cluster owner/admin

Result: Resources Unavailable monitoring links

Other details that may be helpful: v2 monitoring

Environment information

Rancher version (rancher/rancher/rancher/server image tag or shown bottom left in the UI): 2.5.6
Installation option (single install/HA): HA

**Cluster information**
Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom RKE
Kubernetes version (use kubectl version): 1.19.7
Local or downstream cluster: Local 1.19.7, downstream 1.19.7 1.18.15 and 1.20.4 (all same issue) 

**Helm Chart Information**
Version: 2.5.6
Which version of Rancher did you initially install this chart in? 2.4.x
Which version of Rancher did you perform the last upgrade / install of this chart in? 2.5.5 --> 2.5.6

**Comment by nickvth** [comment]
@aiyengar2 we already migrate to monitoring V2 at version 2.5.3 and do all migrations steps. 
It was working in 2.5.5 and UI links in 2.5.6 are not working anymore.

**Comment by aiyengar2** [comment]
Thanks for the confirmation! Another question: are all of your clusters private clusters (like @aquam8 and @bluemalkin)?

Based on some offline discussion with @bluemalkin on the user Slack, it’s possible that you might need to create firewall rules to allow pods to communicate with Alertmanager, Prometheus, and Grafana at their respective ports (9093, 8080, 8080).

**Comment by aquam8** [comment]
My cluster in EKS is private but I do not see any XHR requests in the browser failing, all return 200. Wouldn't I see some errors if it was a permission/FW issue?

Also don't forget that a handbuilt URL request work, like the one Nick pasted: `https://[fqdn]/k8s/clusters/[cluster-id]/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-grafana:80/proxy/?orgId=1`
That works for me too.

PRoblem for me appears just to be the link being disabled. I am also the local admin user in rancher-server - not a normal/default user account.

**Comment by slickwarren** [comment]
I was able to deploy monitoring v2 on 2.5.6 HA using a private EKS cluster. I tried with both a private EKS deployed through rancher and imported. 
After those successfully deployed monitoring, I tested:
* v2.5.5 HA rancher
* deployed private EKS cluster (one hosted, one imported)
* deployed monitoring v2
* upgraded rancher to 2.5.6
which was also able to run monitoring v2 with no issues before and after the upgrade.

**Comment by aquam8** [comment]
Thank you @slickwarren for trying to reproduce!

I'll try that again. How did you install Monitoring V2? From
Rancher's App & Marketplace manually? Or Continuous Delivery/fleet?

Thank you

**Comment by slickwarren** [comment]
no problem! I installed monitoring through the Apps & Marketplace in each of the above cases.

**Comment by nickvth** [comment]
@slickwarren what if you use custom values for example Disable alertmanager and not deploy default alert rules?

**Comment by marcinbojko** [comment]
Same effect in 2.5.7. All network connectivity between nodes are allowed (tcp/udp), monitoring deployed from Apps, redeployed both with and without alertmanager, resources are still unavailable for cluster admin

**Comment by aquam8** [comment]
Hi @slickwarren 

I did uninstall all my monitoring resources in the downstream cluster, and then install Monitoring through the App & Marketplace (was using CD/fleet). Helm deployment was successful. But the links to Grafana/more were all unavailable.
The other options in the menu showed some resources tho.

I included some screenshots:
![Screen Shot 2021-03-16 at 12 15 20 pm](https://user-images.githubusercontent.com/181863/111241664-b3167b00-8651-11eb-96c2-44a22956d110.png)
![Screen Shot 2021-03-16 at 12 14 16 pm](https://user-images.githubusercontent.com/181863/111241669-b6116b80-8651-11eb-936e-04fd5424a16b.png)
![Screen Shot 2021-03-16 at 12 15 04 pm](https://user-images.githubusercontent.com/181863/111241668-b578d500-8651-11eb-888a-d3ea0a4514a5.png)

But as you can see the handcrafted URL works:
![image](https://user-images.githubusercontent.com/181863/111241996-5e273480-8652-11eb-9f81-cdb04e3390d5.png)

**Comment by nickvth** [comment]
@aiyengar2 any progress in finding a solution? We can't upgrade other clusters right now because of this bug.

**Comment by gaktive** [comment]
@Jono-SUSE-Rancher this non-UI ticket likely needs to be transferred to rancher/rancher but based on all the current activity, moving it may confuse folks. How should we handle this: leave it here or move it?

**Comment by aiyengar2** [comment]
@nickvth we haven't been able to reproduce it yet, so I haven't been able to find a solution.

To my knowledge, I don't think this is just a permissions issue. I think this is related to some additional ports that need to be opened in private clusters for 2.5.6 (re: https://github.com/rancher/dashboard/issues/2494#issuecomment-794945559) to access links exposed by Pods on the Rancher UI. This is possibly due to changes introduced in rancher/rancher, since the link URLs are based on proxies executed by the Rancher API, but I am unsure until we are able to reproduce.

@slickwarren any update w.r.t. being able to reproduce this issue?

**Comment by amoebaworks** [comment]
I have a brand new 2.5.6 install and installed Monitoring via the Apps & Marketplace and have the Resource Unavailable situation too. I've uninstalled and reinstalled in different Projects with no change. Btw, what is the difference in installing in System Project vs not in a Project?

**Comment by mkutlak** [comment]
I have this issue on v2.5.8 (On CentOS8 provisioned with RancherD). If I disable Alertmanager, all links show "Resources unavailable". If I enable Alertmanager again, the links work.

**Comment by aquam8** [comment]
Oh good pick up. I have alert manager disabled - I will try enabling it

Thanks!

**Comment by gaktive** [comment]
Any luck @aquam8 after you had enabled alert manager?

**Comment by marcinbojko** [comment]
@gaktive after enabling alert manager, works as expected

**Comment by edward-bear** [comment]
I had the same issue. I enabled Alertmanager and that allowed the UI Buttons to function as expected.

**Comment by pehbehbeh** [comment]
How do you enable Alertmanager? Are you talking about the "Deploy Alertmanager" from the Helm Chart? I had no luck with that.

**Comment by aquam8** [comment]
I deployed using the rancher-monitoring helm
Chart which has alertManager.enabled: true by default. But I had explicitly
set it to false as I wasn’t interested in it initially. After removing that
and redeploying the links started today show.

Hope that helps

**Comment by brunoguidone** [comment]
Hey guys, No luck here.. I'm still getting the same issue with Resource Unavailable message..
The Helm installation was successfull. I can see that the pods and resources were created.
In my case, I'm not using HA mode as the thread but still, I got the same message as you.

Any suggestions ? Thanks!

![image](https://user-images.githubusercontent.com/16587214/123278427-4f67dd80-d4dd-11eb-95ab-3526d98190aa.png)

**Comment by infinytum** [comment]
I can confirm that enabling alert manager in the chart is fixing the links for me.

**Comment by bluemalkin** [comment]
Has anyone managed to get this to work on a private GKE cluster ? Enabling Alert Manager does not fix the issue.

**Comment by bluemalkin** [comment]
Update: I enabled FW logging on TCP and managed to add some rules which made the links work again in Monitoring on a private GKE cluster.

I added the following TCP ports:
* 9093
* 8080
* 8081

Source range: the Kube API master plane
Target: the pod range (using target tags in GKE).

**Comment by brunoguidone** [comment]
Did the same as bluemalkin (thanks!), now it's working on my private clusters (GKE).

**Comment by gaktive** [comment]
Transferring this long-running ticket to the backend since it's not UI related, as evidenced by the workaround.

For now, docs should be updated with the workaround per https://github.com/rancher/dashboard/issues/2494#issuecomment-873741761 since that appears to work.
