### ISSUE TITLE
rke2 - Creating cluster from edit as yaml should redirect users to clusters page once the configs are saved 

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#3093]
Rancher Version: master-f90b36efb4cf50088e63e081e359ddd9b94c8ecf-head
1. From cluster explorer --> Create rke2 node driver cluster 
2. Click on edit as yaml in the cluster and provide the configurations
3. Once we click on save, we are not re-directed to the cluster management page but remain on the cluster yaml page. Users should be re-directed to clusters page once we click on save

https://user-images.githubusercontent.com/38144301/119578044-a3619400-bd70-11eb-901c-c13b3bc01e98.mov

**Comment by vincent99** [comment]
This looks to have been fixed a while ago.

**Comment by anupama2501** [comment]
@vincent99 

I still see the issue on master-head 

- From cluster explorer --> Create rke2 node driver cluster
- Click on edit as yaml in the cluster and provide the configurations
- Once we click on **create**, we are not re-directed to the cluster management page but remain on the cluster yaml page. Users should be re-directed to clusters page once we click on **create**

With the configurations as yaml , cluster created:
<img width="400" alt="Screen Shot 2021-06-30 at 1 33 37 PM" src="https://user-images.githubusercontent.com/38144301/124007722-a07a4480-d9a9-11eb-825d-34628d69cfc6.png">

If we navigate back to the cluster management page, we see the cluster is created:
<img width="400" alt="Screen Shot 2021-06-30 at 1 35 53 PM" src="https://user-images.githubusercontent.com/38144301/124007874-cc95c580-d9a9-11eb-9194-d0a69c941988.png">

**Comment by anupama2501** [comment]
verified on v2.6-head e3316c9, upon creation users are redirected to cluster-management page
