### ISSUE TITLE
OPA enable page goes away if I move away and come back to page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#353]
Date - 3/5

Steps:
1.  Go to new Dashboard
2.  Click on OPA+Gatekeeper in Left Nav
3.  Click on Namespace in Left Nav and click on OPA+Gateway again

Results: OPA + Gatekeeper is not available in the system-charts catalog.
![image](https://user-images.githubusercontent.com/11514927/76037085-28118980-5f03-11ea-9582-078616dd13d5.png)

**Comment by westlywright** [comment]
Can you test this again on the latest master (front end and back)? I can't repro so I think it was resolved by some framework/api changes made recently.

**Comment by tfiduccia** [comment]
@westlywright - On the current build (just built new one) I'm still seeing this.  I literally just go to OPA, Namespace then back to OPA.  OPA must be disabled (think I forgot this part when I originally entered).

**Comment by tfiduccia** [comment]
Fixed
