### ISSUE TITLE
vmware rke1 cluster is reported as AmazonEC2 in cluster management ui

### ISSUE THREAD

**Issue by ibrokethecloud** [rancher/dashboard#3731]
**Rancher Server Setup**
- Rancher version: master-head and v2.6-head
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): k3s
- Proxy/Cert Details: letsEncrypt

**Information about the Cluster**
- Kubernetes version: v1.21.3+k3s1
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Vmware infra provider

**Describe the bug**

When using master-head or v2.6-head to provision a RKE1 cluster on vmware, the cluster provisions correctly, however the cluster management UI reports the Provider as Amazon EC2.

**To Reproduce**
 
Launch a RKE1 cluster on vsphere.

**Result**
Expect the provider to be reported as vmware in the UI.

**Expected Result**

**Screenshots**

![image](https://user-images.githubusercontent.com/19664014/128120232-63b88649-489a-4f95-9173-a14b2132c5aa.png)
![image](https://user-images.githubusercontent.com/19664014/128120330-190e548c-ff8f-4945-9b21-7369f42e8597.png)
![image](https://user-images.githubusercontent.com/19664014/128120370-a6a6bbe4-7832-4de0-abcc-0c5ce6502065.png)

**Additional context**
<!--Add any other context about the problem here.—>

**Comment by deniseschannon** [comment]
Given that the nodetemplatespec has the correct info, I've transferred this to dashboard, but if it's a backend issue, please let us know.

**Comment by deniseschannon** [comment]
@ibrokethecloud Do you have a setup to share around this as my setup shows my RKE1 DO cluster fine.

**Comment by codyrancher** [comment]
I attempted to reproduce on vsphere but the provider was correct. I'll try a couple other RKE1 providers before moving to test.

<img width="1435" alt="Screen Shot 2021-08-09 at 5 12 34 PM" src="https://user-images.githubusercontent.com/55104481/128789727-a2bb37ec-2a95-463d-b1e6-d0dfdf6a752d.png">

**Comment by codyrancher** [comment]
I saw the same behavior with digital ocean. I think this may have been resolved by some other work.

![Screenshot from 2021-08-09 17-48-45](https://user-images.githubusercontent.com/55104481/128791961-c04fb498-4bde-4ad6-b975-8a9a40f3d5ca.png)

**Comment by deniseschannon** [comment]
@ibrokethecloud Can you try with the latest v2.6-head and let me know if you are still seeing the same issue?

**Comment by ibrokethecloud** [comment]
Hi @deniseschannon just tried on v2.6-head (723f747) and I still see the same issue.

Both my digitalocean and vmware rke1 clusters report provider as AmazonEC2.

<img width="1202" alt="image" src="https://user-images.githubusercontent.com/19664014/128811039-2f84a6ed-75c1-4f54-84c7-218d803bcbbb.png">

**Comment by richard-cox** [comment]
Probably related to #3714

**Comment by richard-cox** [comment]
Try creating the cluster after clicking around the different provides.

**Comment by deniseschannon** [comment]
@ibrokethecloud Can you test again with v2.6.0-rc3 to see if you can reproduce it?

**Comment by anupama2501** [comment]
Verified on v2.6-head 72986b2 and v2.6.0-rc3

cloud providers show up as expected for vsphere and DO 

<img width="600" alt="Screen Shot 2021-08-17 at 3 28 08 PM" src="https://user-images.githubusercontent.com/38144301/129808936-6ebb5440-8904-4fbd-bead-2490fdc3c0df.png">
