### ISSUE TITLE
Multiple same versions of CSI/CPI charts show up when the rancher feature chart repo is changed to point to dev-v2.5-vsphere-release

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#4579]
Setup

Rancher version: 2.5.11
Browser type & version: Chrome

**Describe the bug**
When we change the rancher feature chart repo branch to `dev-v2.5-vsphere-release`, I see multiple same versions of CSI/CPI charts displayed. If we upgrade either of the CSI/CPI charts to a later version, then it goes back to displaying 1 version each.

**To Reproduce**
1. Install CPI charts version `1.0.000` and CSI `v2.1.000` from apps & market
2. Change the rancher feature chart branch to `dev-v2.5-vsphere-release`
3. Go back to apps & market to upgrade the chart version

**Result**
Multiple same versions of the chart show up

**Expected Result**
Expected to show 1 version but not multiple same versions of the charts.

**Screenshots**
Before upgrading a CSI chart:
<img width="300" alt="Screen Shot 2021-11-16 at 12 10 10 PM" src="https://user-images.githubusercontent.com/38144301/142258773-b5675f12-903f-44a7-8177-5cab57a64fdd.png">

Post upgrade CPI chart

<img width="300" alt="Screen Shot 2021-11-16 at 12 19 00 PM" src="https://user-images.githubusercontent.com/38144301/142259241-4cb5caa7-9114-4952-852c-0fc4aef98303.png">

**Additional context**
If we select any of the version from the multiple versions of the chart, the chart displays correctly with 1 version of all the required versions.
This does not happen all the time. I tried switching the branch back to release-v2.5 and back to `dev-v2.5-vsphere-release` but I did not see this issue.

**Comment by gaktive** [comment]
@anupama2501 if you look at the same repo via the Helm command, do you see duplicates occasionally there too? Is there any other pattern to replicating? You mention that it doesn't happen all the time but are there possible other events or load on this cluster?

And since you tagged this as 2.6.3, is this also happening in that version along with 2.5.11?

**Comment by richard-cox** [comment]
I couldn't reproduce this with the latest 2.6 code. In the 2.x time frame this whole process was re-worked though, chance are it was fixed along the way

**Comment by vivek-infracloud** [comment]
### Issue is still reproducible on rancher v2.5-head (777b5d). 

**Steps To Reproduce**

- Install CPI charts version 1.0.000 and CSI v2.1.000 from apps & market
- Change the rancher feature chart branch to dev-v2.5-vsphere-release
- Go back to apps & market to upgrade the chart version

**Result**
**Same version of the chart show up twice.** 

CPI Chart versions screenshot
![Screenshot from 2021-12-23 10-30-13](https://user-images.githubusercontent.com/83208989/147191544-9ceb8db8-2612-4106-bd4f-33dce4fd06e5.png)

CSI Chart versions screenshot
![Screenshot from 2021-12-23 10-30-21](https://user-images.githubusercontent.com/83208989/147191826-35f3d943-b3a6-4457-862f-ed207a052b5b.png)

**Expected Result**
Expected to show only 1 version of chart.

**Comment by richard-cox** [comment]
I cannot (also) reproduce this in 2.5-head (edf83d5). @vivek-infracloud Can you provide click by click steps to reproduce? I'm working on the following assumptions
- Charts are installed to a downstream cluster
- Charts in question are `vSphere CPI` and `vSphere CSI` both from the `Rancher` helm chart repo
- The 'Git Branch` of the `Rancher` `Chart Repository` is what's updated from `dev-v2.5` to `dev-v2.5-vsphere-release`
- Once the `Git Branch` is updated user gets to the `Upgrade x` page by navigating to `Installed Apps` --> <version tag> in the `Upgradable` column

Could you also provide a copy of the `console` output from the browser's dev tools? I particularly interested if a `Loading index for repo ... ` line appears sometime after changing the `Git Branch`

Looking at the code duplicate entries in the dropdown could appear if the catalog action `load` is called, the repo in question is re-fetched and the existing charts cache is used... but there doesn't seem to be a way this can happen (`force` and `reset` will always be true together and the `loaded` mechanism looks solid).

**Comment by vivek-infracloud** [comment]
@richard-cox I tried to reproduce this again just now on v2.5-head(edf83d5). However, even I could not reproduce it this time. 
Chart versions do not show up twice.

CPI Chart versions screenshot
![Screenshot from 2022-01-04 18-52-25](https://user-images.githubusercontent.com/83208989/148066066-59560475-5bc4-46d9-aa7e-480088d4ded6.png)

CSI Chart versions screenshot
![Screenshot from 2022-01-04 18-52-35](https://user-images.githubusercontent.com/83208989/148066135-db942125-e78d-44da-be62-42ad29bf55fd.png)

**Comment by richard-cox** [comment]
@vivek-infracloud The joys of tech. Ok, I'm bumping back to re-test for reproducing, confirmation of steps and additional information from https://github.com/rancher/dashboard/issues/4579#issuecomment-1004734275. If it can't be reproduced suggest we close.

**Comment by anupama2501** [comment]
Closing this ticket as this is not reproducible again.
