### ISSUE TITLE
Cluster Tool apps remain in side nav after app is uninstalled

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#4849]
- After installing some cluster tools (e.g. logging, longhorn, etc) they automatically appear in the side nav in the same session
- After deleting these apps the menu items remain in the side nav _until the page is refreshed_
  - Note - Some apps have sibling `<x>-crd` apps. Following on from https://github.com/rancher/dashboard/pull/4100 these both can be deleted concurrently from the `Cluster Tools` page

Help with navigating to the page since I had forgotten we moved the page:
![Image](https://github.com/user-attachments/assets/832c2c24-7651-4fc1-97cb-a2a229fc6ade)

**Comment by nwmac** [comment]
Looks to me like the CRDs are not actually removed when you check the checkbox.

**Comment by nwmac** [comment]
Suggest we tackle this as part of refactoring the side nav

**Comment by gaktive** [comment]
@richard-cox may have fixed this via other work so we need to validate that this is working now.

**Comment by richard-cox** [comment]
It could have been this one https://github.com/rancher/dashboard/pull/6784, which included a QA validation step to ensure the side nav updated when `CIS Benchmark` was installed/uninstalled

**Comment by nwmac** [comment]
@jordojordo Can you validate this - see below - believe this has been fixed - if so, can you change the milestone to 2.6.9 and move to test.

**Comment by jordojordo** [comment]
As of `v2.6-a3b5237ce1da4228c97df7552d57464c64947b3b-head` the items will still persist on the side nav until the page is refreshed. Tested with `CIS Benchmark`, `Longhorn`, and `Logging`.

**Comment by catherineluse** [comment]
@jordojordo So, the page that generates the side nav - `shell/layouts/default.vue` - uses 13 watchers to update the side nav. We should avoid watchers wherever possible because the vast majority of the time, a computed property would use less memory and would be cleaner code. In my opinion, all 13 of those watchers should be computed properties, which is why I would agree with Neil's comment that it would be justified to address this issue as part of a larger refactor.

One of the watchers is for `allSchemas`:

```
allSchemas(a, b) {
      if ( a !== b ) {
        this.queueUpdate();
      }
    },
```

In theory, that is what should cause the links to be removed from the side nav, because when no schemas are available with Helm chart specific prefixes such as `cis.cattle.io`, those should disappear. But in my local testing, the code in that watcher never ran after installing OR uninstalling Helm charts, and the side nav did not update until I navigated to the home page and back.

I believe the short term fix would be to figure out why the code in the `allSchemas` watcher is no longer running, and fix that. But if we really want the the side nav to be generated from schema changes, the ideal way to do it would be to have a `groups` computed property instead of a `getGroups` method.

**Comment by richard-cox** [comment]
The associated PR for this has been closed

**Comment by richard-cox** [comment]
We should pause on this one until https://github.com/rancher/dashboard/pull/10008 merges. It contains changes to the watches which might resolve this issue

**Comment by codyrancher** [comment]
@richard-cox I think we should close this, we no longer have cluster tools and extensions (the closest analog) requires the user to refresh the page after the extension has been uninstalled.

**Comment by richard-cox** [comment]
The cluster tools page has moved to the Cluster group's Tools page.

Might have been resolved though, is it still reproducible?

**Comment by codyrancher** [comment]
I'll take a look.

**Comment by nwmac** [comment]
I think this related to when you installed something like monitoring and then uninstalled it, the nav item still showed up.

This used to be because uninstalling did not remove CRDS and that is why we use to determine if we should show the nav item.

**Comment by codyrancher** [comment]
> I think this related to when you installed something like monitoring and then uninstalled it, the nav item still showed up.
> 
> This used to be because uninstalling did not remove CRDS and that is why we use to determine if we should show the nav item.

Yeah, it looks like that's still happening. I just checked with logging and after uninstalling even after refreshing the items remain in the explorer navigation.

**Comment by jordojordo** [comment]
This is by design from Helm: https://helm.sh/docs/topics/charts/#limitations-on-crds

>CRDs are never deleted. Deleting a CRD automatically deletes all of the CRD's contents across all namespaces in the cluster. Consequently, Helm will not delete CRDs.
Operators who want to upgrade or delete CRDs are encouraged to do this manually and with great care.

We would either have to delete them manually or find an alternative to determine if the nav item should be shown.

**Comment by nwmac** [comment]
Yeah - we mostly have 2 charts because of this - 1 for the CRDS and one for the app itself and we only uninstall the 2nd.

Maybe we need to check the uninstall - I thought for apps, we offered to uninstall the CRDs via a checkbox.

**Comment by codyrancher** [comment]
We don't offer the option on the tools page. In fact we don't even show the display name for the tool when uninstalling and call it deleting.

![Image](https://github.com/user-attachments/assets/adf6acae-b749-472b-a242-18eec7e597c6)

**Comment by jordojordo** [comment]
We do have a checkbox for [uninstalling the CRDs](https://github.com/rancher/dashboard/blob/2783cfcaeffb15e322155786b6a01ee9c75be175/shell/components/PromptRemove.vue#L410-L416) which is [determined by a few conditions](https://github.com/rancher/dashboard/blob/2783cfcaeffb15e322155786b6a01ee9c75be175/shell/components/PromptRemove.vue#L166-L174). It's odd that isn't showing up now.

**Comment by richard-cox** [comment]
> Looks like some things were shifted around [a long time ago](https://github.com/rancher/dashboard/commit/220cc89bdd956a58eb882a05fd5a605c05ed3b74#diff-c7e47fb2ccabb10266e97ac71e4ced06922eb3d8bc03bacd9815887aa185b3d7R410), this is overriding some messages and inputs from showing.

The bug is in [this](https://github.com/rancher/dashboard/blob/master/shell/components/PromptRemove.vue#L170) line. `this.currentRouter?.currentRoute` has no name. Now it looks like it should be `this.currentRouter?.currentRoute?.value?.name`

**Comment by yonasberhe23** [comment]
Manual validation required. Followup task to add e2e coverage created https://github.com/rancher/qa-tasks/issues/1698

**Comment by yonasberhe23** [comment]
User has option to uninstall both chart and/or crd at once via the new modal option.
Uninstall of chart or both successful. 
 
Tested in:

- Rancher v2.11-bff2809d433c014a595d024f76fd7eabbbfa3013-head
- Dashboard master `ffe0996`

https://github.com/user-attachments/assets/7859b229-0af4-46a8-8034-7edcc68f90f6
