### ISSUE TITLE
Add forms for configuring project-level alerting

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#5588]
Screenshots:
AlertmanagerConfig detail page has tabs for receivers and route:
<img width="1247" alt="Screen Shot 2022-04-26 at 6 02 58 PM" src="https://user-images.githubusercontent.com/20599230/165417893-591b989c-2c52-42af-8831-1755edb967ee.png">

Edit receiver as YAML lets you edit the whole AlertmanagerConfig YAML:
<img width="1253" alt="Screen Shot 2022-04-26 at 6 03 52 PM" src="https://user-images.githubusercontent.com/20599230/165417882-df047a5b-e9bc-4529-abbe-c0101d4d0fb8.png">

For editing receivers, the forms look much the same as the existing Receiver forms, except the header says it is within an AlertmanagerConfig:
<img width="1212" alt="Screen Shot 2022-04-26 at 6 02 44 PM" src="https://user-images.githubusercontent.com/20599230/165417894-d3f0b79a-61ce-41d2-85c3-f6db345a9bee.png">

The other difference for receiver config is that secret selectors will be used for editing sensitive details, but that will be finished in a separate PR:
<img width="1276" alt="Screen Shot 2022-04-26 at 6 03 33 PM" src="https://user-images.githubusercontent.com/20599230/165417892-ec3f2db4-44c5-4077-b74e-c001de261929.png">

A receiver cannot be created until an AlertmanagerConfig is created, for the MVP at least. So before the AlertmanagerConfig is created, the Add Receiver button is disabled and has a tooltip explaining why:
<img width="1278" alt="Screen Shot 2022-04-26 at 6 02 10 PM" src="https://user-images.githubusercontent.com/20599230/165417896-b4433a68-1852-4eae-b3f1-2e35557e778e.png">

After the AlertmanagerConfig is created, the Add Receiver button works:
<img width="1196" alt="Screen Shot 2022-04-26 at 6 02 33 PM" src="https://user-images.githubusercontent.com/20599230/165417895-604506b7-746d-4f7c-a983-797c6437123b.png">

The AlertmanagerConfig list page is mostly empty for now, but in a separate PR I will add details to preview what receivers are configured in it with icons for them:
<img width="1405" alt="Screen Shot 2022-04-26 at 6 01 44 PM" src="https://user-images.githubusercontent.com/20599230/165417897-ac7bfc98-e17e-424d-ab09-0b10859fd23b.png">

The existing Routes and Receivers page says deprecated on it and there's a banner saying to use AlertmanagerConfigs instead:
<img width="1394" alt="Screen Shot 2022-04-26 at 6 07 17 PM" src="https://user-images.githubusercontent.com/20599230/165417973-f6084abc-2380-46a4-afc2-9840620ee6db.png">

**Comment by catherineluse** [comment]
This issue includes https://github.com/rancher/dashboard/issues/2612 in the scope of it.

**Comment by catherineluse** [comment]
These forms were mostly completed in https://github.com/rancher/dashboard/pull/5712 and https://github.com/Sean-McQ/dashboard/pull/1. Here's what is able to be validated so far:
# QA Template
## What was fixed, or what changes have occurred
- In the side nav of cluster explorer, when project monitoring is intalled, AlertmanagerConfigs should show in the side nav
- You should be able to create, edit and delete AlertmanagerConfigs in forms or in YAML
- In the list view for AlertmanagerConfigs, clicking a name in the list goes to the AlertmanagerConfig detail page
- On the AlertmanagerConfig detail page, there are two tabs for route and receiver
	- On the Receivers tab, you can see receivers listed. The ⋮ button lets you go Edit Config, Edit YAML and Delete for each receiver. Note: The Edit YAML should let you edit the entire AlertmanagerConfig because the receiver isn't a separate resource.
	- On the Receivers tab, the name of the receiver goes to the receiver detail page with an overview of the different receiver types - Slack, PagerDuty etc.

## Areas or cases that should be tested
- On the Route tab, you can fill out details in the route form and see changes reflected in the AlertmanagerConfig YAML. The resulting YAML should match the structure defined in the API docs: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#route
- From the receiver detail page you can go to View YAML, Edit YAML, Edit Config and delete.
- When a reciever is added or deleted, the list of receivers in the AlertmanagerConfig detail page should be updated.
- Any edits to receivers should be immediately reflected in the AlertmanagerConfig YAML.

### What should not be tested yet
- The receiver detail forms can't be tested yet because on each receiver config form, every sensitive field (such has Slack webhook URL) has to have a working secret selector instead of a regular input field. Those changes are coming in a separate PR.
 
## What areas could experience regressions?
- There were changes to the action menu (the ⋮ button), which is used all over Rancher, so that button could be checked on other pages (such as in cluster manager list views) just to make sure it still opens and renders normally

**Comment by ronhorton** [comment]
still cannot add grouping and matching via the form; adding groupby in yaml, tho, shows on the form and is editable. 
<img width="1367" alt="Screen Shot 2022-05-06 at 11 20 56 AM" src="https://user-images.githubusercontent.com/89212856/167163250-ce6585d3-3b3b-483f-a725-3e0dd223a737.png">

**Comment by catherineluse** [comment]
This should work now that https://github.com/rancher/dashboard/pull/5854 has been merged. Sorry, I forgot that that wasn't merged yet.

**Comment by ronhorton** [comment]
**Pass**
verified in `2.6-head Commit ID 132b182`
