### ISSUE TITLE
[UI] - Paginitation regression

### ISSUE THREAD

**Issue by sebastienroul** [rancher/dashboard#6027]
**Setup**
- Rancher version: 2.6.5
- Browser type & version: All

**Describe the bug**
From 2.6.5 the UI list doesn't respect the "Table row per page" but always use 10 as default value

This is a regression compare to previous 2.6.5

In 2.6.4 with 100 in the settings
![image](https://user-images.githubusercontent.com/2582255/170026534-9456e5c9-04de-4929-86ac-67cad5357702.png)

Now in 2.6.5 with 100 in the settings
![image](https://user-images.githubusercontent.com/2582255/170026604-983352ce-5df9-46be-9530-db624c3e4ce2.png)

**Comment by richard-cox** [comment]
I had a quick look on our latest `2-6.head` and this looks like it was resolved. We need to confirm this.

@sebastienroul Could you confirm what the `per-page` value is when you load `<rancher url>/v1/userpreferences` in your browser? Does it get updated when you change the `table row per page` preference in the UI (and refresh `v1/preferences`)?

**Comment by sebastienroul** [comment]
@richard-cox 

I confirm : 100
![image](https://user-images.githubusercontent.com/2582255/170037199-acc74107-6460-4f41-9307-0165436dbf2d.png)

And it is updated when using UI

![image](https://user-images.githubusercontent.com/2582255/170037311-88187d42-6a9f-43ab-a4f2-25ef219e6de4.png)

**Comment by sebastienroul** [comment]
Hi @richard-cox 

Just upgrade to 2.6.6, and the problem is still there.

Here is my /v1/userpreferences
![image](https://user-images.githubusercontent.com/2582255/177249533-57c36166-7e9d-4004-a079-bba92f092e72.png)

and the result
![image](https://user-images.githubusercontent.com/2582255/177249675-7c6fe80d-93b7-4f57-b87e-c3a45d8614f7.png)


Let me know if there any hack cause it's very painful.

Best regards

**Comment by richard-cox** [comment]
I can't find the PR, but this was related to the `select` issue that was apparent with the log streaming timeframe setting and was resolved by the same fix.
I couldn't reproduce in 2.6-head, so moving to QA to validate for the next release

**Comment by sebastienroul** [comment]
Hi @richard-cox 

Your're right, it's the same "kind of" issue - to fix it : <your rancher url>/v3/preferences/per-page pressing the delete button on the right of the page and then send request in the modal that pops up.

The stange point is that my rancher install (2.6.6) is totally new (from yesterday) - so the rootcause of this wrong setting is not found.

Hope it helps.

**Comment by brandonsuse** [comment]
@richard-cox Could you please add a QA template for this ticket when you get a chance? Thanks!
CC: @AndrewHoffmanQA

**Comment by richard-cox** [comment]
# QA Template

## Root cause
See https://github.com/rancher/dashboard/issues/5984#issuecomment-1132511208
 
## What was fixed, or what changes have occurred
See https://github.com/rancher/dashboard/issues/5984#issuecomment-1132511208
 
## Areas or cases that should be tested
1. Navigate to a Clusters Workloads page, ensure there are over 25 rows in the table
2. Navigate to the User Preferences page and change the `Table Rows per Page` setting to 10
3. Navigate back to the Clusters Workloads page and observe the the pagination controls at the bottom of the list state `1 - 10 of <x> workloads` and only 10 rows are showing
4. Navigate back to the User Preferences page and change the `Table Rows per Page` setting to 25
5. Navigate back to the Clusters Workloads page and observe the the pagination controls at the bottom of the list state `1 - 25 of <x> workloads` and only 25 rows are showing

 
## What areas could experience regressions?
All lists
 
## Are the repro steps accurate/minimal?
See steps above

**Comment by AndrewHoffmanQA** [comment]
tested in 2.6.7-RC1, UI now correctly shows 1-100 is set in the user profile and a page has 100+ line items.

**Comment by richard-cox** [comment]
Tagging original issue https://github.com/rancher/dashboard/issues/5984
