### ISSUE TITLE
List column header tooltip isn't centred on column header

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#7873]
**Setup**
- Rancher version: 2.7-head (2.7next1 timeframe)
- Browser type & version:

**Describe the bug**
See screenshot

**To Reproduce**
- Go to `Events` list
- hover cursor over `Last Seen` column header (others have issue to)

**Result**
See screenshot

**Expected Result**
tooltip location should be based on column header text

**Screenshots**
![image](https://user-images.githubusercontent.com/18697775/211338884-f86bfd58-6f49-42d5-9753-82239851cd9f.png)

**Comment by jameson-mcghee** [comment]
When testing on `v2.7-head` (Commit ID: ), I was unable to see a tooltip being generated at all for the _State_, _Last Seen_, _Type_, _Reason_, _Message_, _Name_, or _Namespace_ column headers. I am uncertain if the other headers should have column headers should have tooltips or not (perhaps you can reply with that information @richard-cox), but I am Reopening this ticket due to the absence of a tooltip for the _Last Seen_ column header.

![2023-01-13_17-14-29](https://user-images.githubusercontent.com/13294321/212429136-a321ae58-6d3a-4217-b366-d03b6e365ca1.gif)

**Comment by bisht-richa** [comment]
@jameson-mcghee I checked the UI, and not all the column headers have tooltips. I think when the card was created _Last Seen_  had, but now no tooltip text coming from API that's why it is not showing. The card was to fix the position of the tooltip for column headers if there were any.

**Comment by bisht-richa** [comment]
@jameson-mcghee Issue related to this card is fixed. Need to create another ticket for the issue of missing tooltip for the Last Seen column header. As the tooltip is missing from the API.

**Comment by jameson-mcghee** [comment]
> @jameson-mcghee Issue related to this card is fixed. Need to create another ticket for the issue of missing tooltip for the Last Seen column header. As the tooltip is missing from the API.

@bisht-richa, makes sense to me. I am going to do as you recommend (close this ticket and create a new one of the other issue), but wanted to confirm what to add into the new ticket first. Is it just the `Last Seen` column that is missing from the API, or is it all of the column headers that do not generate a tooltip? Just want to verify the scope before creating the new ticket.

**Comment by richard-cox** [comment]
The missing description for `Last Seen` is a bug. When it comes via API it's the resource's schema and column headers `description`. Those still exist for the events schema's (see `<rancher  url>/v1/schema/events`) `Last Seen` column (see `type-map` `fromSchema` for how this happens).

Looks like the column definition  was split from  the schema definition in https://github.com/rancher/dashboard/pull/7893

Would agree this is a separate bug though, @jameson-mcghee would you do the honour of creating a new issue?

**Comment by jameson-mcghee** [comment]
Based on my previous testing as well as comments from @bisht-richa and @richard-cox, I am closing this ticket as Done.

Related issue #7972
