### ISSUE TITLE
Issues in Deploying ECM page

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#919]
**Issue#1**
- ECM is incorrectly spelled `Enterpise Cluster Manager Feature` --> missing an `r`
<img width="1459" alt="Screen Shot 2020-07-29 at 10 43 50 AM" src="https://user-images.githubusercontent.com/26032343/88834405-a0196e00-d188-11ea-815b-8d4b08788833.png">

**Issue#2**
- Namespace and Name text fields' texts -- look like they are disabled/User has to enter the value
- Namespace and Name text fields' texts and the Description text field placeholder look alike.
<img width="1459" alt="Screen Shot 2020-07-29 at 10 43 50 AM" src="https://user-images.githubusercontent.com/26032343/88834558-e5d63680-d188-11ea-9674-d78a01b3e802.png">

**Comment by vincent99** [comment]
The typo is in the chart readme, but I fixed it.

That is what disabled inputs currently look like, but if both the name and namespaced are set and not changeable I just don't show the component anymore.  Same with the version choice if there is only one version.

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `217656d19`**

Typo is still see in `Enterpise Cluster Manager Feature`
<img width="1600" alt="Screen Shot 2020-08-04 at 6 45 52 PM" src="https://user-images.githubusercontent.com/26032343/89362692-5f878c00-d683-11ea-8c18-6bdc64bfc2b7.png">

**Comment by vincent99** [comment]
You're still pointed at `dev-charts` instead of `charts`.

**Comment by sowmyav27** [comment]
- On master-head - Changed the charts to point to `https://charts.rancher.io`
- No typo in `Enterprise Cluster Manager Feature`
<img width="885" alt="Screen Shot 2020-08-05 at 7 19 05 AM" src="https://user-images.githubusercontent.com/26032343/89423950-fdaf3c80-d6eb-11ea-8492-5ecaf0ca1b0f.png">
